name: Stone Soup
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title.html
exclude: [Gemfile, Gemfile.lock, .gitignore, Rakefile]
timezone: Europe/Athens
encoding: UTF-8
relative_permalinks: true

sass:
    style: expanded
    deploy_style: compressed 
    compile_in_place: false

slim:
  pretty: true
